Repository openshift/hac-dev, pull requests merged in 2021-11, with the labels that each got.

#8 Init build/test scripts
  build.sh
  test.sh
Labels: lgtm

#9 Enable typescript validation with eslint and update CI build/test scripts
  .eslintignore
  .eslintrc.js
  .eslintrc.yml
  @types/index.d.ts
  babel.config.js
  build.sh
  package-lock.json
  package.json
  src/App.tsx
  src/store/index.ts
  test.sh
Labels: lgtm, approved

#11 chore: upload code coverage to codecov
  package.json
  test.sh
Labels: lgtm, ok-to-test, approved

#12 Prefix css generated classes with correct namespace
  config/dev.webpack.config.js
Labels: lgtm, approved

#13 Add QE Members As Reviewers
  OWNERS
Labels: lgtm, approved
