Repository openshift/hac-dev, pull requests merged in 2022-08, with the labels that each got.

#158 Use display name for application delete confirmation modal
  src/components/modal/DeleteResourceModal.tsx
  src/components/modal/__tests__/DeleteResourceModal.spec.tsx
  src/components/modal/resource-modals.tsx
Labels: lgtm, approved

#167 Reset detected components if sample tile is deselected
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx
Labels: lgtm, approved

#160 Handle 404 error state in application details view
  src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
  src/components/ApplicationDetailsView/__tests__/ApplicationDetailsView.spec.tsx
Labels: lgtm, approved

#163 rename build logs modal
  src/components/LogViewer/BuildLogViewer.tsx
Labels: lgtm, approved

#164 change Environemnt cards visuals on settings page
  src/components/Environment/EnvironmentCard.tsx
  src/components/Environment/__tests__/EnvironmentCard.spec.tsx
Labels: lgtm, approved

#145 HACBS - Application workflow visualization
  config/dev.webpack.config.js
  package-lock.json
  package.json
  src/components/modal/__mocks__/tabbable.ts
  src/hacbs/components/ApplicationDetails/DetailsPage.scss
  src/hacbs/components/ApplicationDetails/DetailsPage.tsx
  src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
  src/hacbs/components/ApplicationDetails/tabs/ApplicationOverviewTab.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/sections/AppWorkflowSection.scss
  src/hacbs/components/ApplicationDetails/tabs/overview/sections/AppWorkflowSection.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/WorkflowGraph.scss
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/WorkflowGraph.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/WorkflowVisualizationSurface.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/const.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/edges/WorkflowEdge.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/factories.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/index.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNode.scss
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNode.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/types.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/visualization-utils.spec.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/draw-utils.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/node-icon-utils.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts
  src/hacbs/consts/pipeline.ts
  src/hacbs/hooks/index.ts
  src/hacbs/hooks/useBuildPipelines.ts
  src/hacbs/hooks/useComponents.ts
  src/hacbs/hooks/useEnvironments.ts
  src/hacbs/hooks/useIntegrationTestScenarios.ts
  src/hacbs/hooks/useReleaseLinks.ts
  src/hacbs/models/hacbs.ts
  src/hacbs/models/index.ts
  src/hacbs/models/pipeline.ts
  src/hacbs/types/coreBuildService.ts
  src/hacbs/types/coreTekton.ts
  src/hacbs/types/index.ts
  src/hacbs/types/pipeline.ts
  src/hacbs/types/pipelineRun.ts
  src/hacbs/types/task.ts
  src/hacbs/types/taskRun.ts
Labels: lgtm, approved, hacbs

#170 update hacbs wizard navigation
  src/hacbs/components/ImportForm/useImportSteps.tsx
Labels: lgtm, approved, hacbs

#165 Adds quickstart for HACBS applications
  src/hacbs/components/ApplicationDetails/ApplicationQuickstartContent.ts
  src/hacbs/components/ApplicationDetails/DetailsPage.tsx
  src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
  src/hacbs/components/ApplicationDetails/__tests__/HacbsApplicationDetails.spec.tsx
Labels: lgtm, approved, hacbs

#172 Fix PF topology styling in staging environment
  config/prod.webpack.config.js
Labels: lgtm, approved, hacbs

#176 enable code coverage for hacbs
  jest.config.js
  src/hacbs/components/ImportForm/__tests__/ImportForm.spec.tsx
Labels: lgtm, approved, hacbs

#157 Getting started modal HACBS
  src/hacbs/components/Modals/GettingStartedModal.tsx
  src/hacbs/components/Modals/__tests__/GettingStartedModal.spec.tsx
  src/hacbs/components/Modals/imgs/Enterprise-contract.svg
  src/hacbs/components/Modals/imgs/Integration-test.svg
  src/pages/ApplicationsPage.tsx
Labels: lgtm, approved, hacbs

#166 Add Integration test step in App creation wizard
  src/hacbs/components/ImportForm/ImportForm.tsx
  src/hacbs/components/ImportForm/IntegrationTestSection.tsx
  src/hacbs/components/ImportForm/__tests__/useImportSteps.spec.ts
  src/hacbs/components/ImportForm/submit-utils.ts
  src/hacbs/components/ImportForm/types.ts
  src/hacbs/components/ImportForm/useImportSteps.tsx
  src/hacbs/components/ImportForm/utils/__tests__/submit-utils.spec.ts
  src/hacbs/components/ImportForm/utils/validation-utils.ts
  src/hacbs/models/hacbs.ts
Labels: lgtm, approved, hacbs

#178 Show validation errors on application/component creation
  src/hacbs/components/ImportForm/BuildSection.tsx
  src/hacbs/components/ImportForm/ImportForm.tsx
  src/hacbs/components/ImportForm/IntegrationTestSection.tsx
  src/hacbs/components/ImportForm/create-utils.ts
  src/hacbs/components/ImportForm/useImportSteps.tsx
  src/hacbs/components/ImportForm/utils/__data__/application-data.ts
  src/hacbs/components/ImportForm/utils/__tests__/create-utils.spec.ts
  src/hacbs/components/ImportForm/utils/__tests__/submit-utils-spec.ts
  src/hacbs/components/ImportForm/utils/submit-utils.ts
  src/shared/components/formik-fields/EditableLabelField.tsx
  src/shared/components/formik-fields/__tests__/EditableLabelField.spec.tsx
Labels: lgtm, approved

#180 render log viewer in PLR logs tab
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunLogsTab.tsx
Labels: lgtm, approved, hacbs

#181 add task runs list to pipelinerun details
  src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunTaskRunsTab.tsx
  src/hacbs/components/TaskRunListView/TaskRunListHeader.ts
  src/hacbs/components/TaskRunListView/TaskRunListRow.tsx
  src/hacbs/components/TaskRunListView/TaskRunListView.tsx
  src/hacbs/components/TaskRunListView/__data__/mock-TaskRun-data.ts
  src/hacbs/components/TaskRunListView/__tests__/TaskRunListRow.spec.tsx
  src/hacbs/components/TaskRunListView/__tests__/TaskRunListView.spec.tsx
  src/hacbs/types/taskRun.ts
  src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx
Labels: lgtm, approved, hacbs

#169 Avoid creating binding when provider is unknown
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
Labels: lgtm, approved

#173 Update empty state image for application list
  @types/index.d.ts
  src/components/ApplicationListView/ApplicationListView.tsx
  src/imgs/application-list-empty.png
Labels: lgtm, approved

#177 use context provider for Namespace
  config/remotePlugin.js
  src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
  src/components/ApplicationDetailsView/ComponentDetails.tsx
  src/components/ApplicationDetailsView/ComponentListView.tsx
  src/components/ApplicationListView/ApplicationListView.tsx
  src/components/ComponentSettingsForm/ComponentSettingsView.tsx
  src/components/Environment/EnvironmentListView.tsx
  src/components/Environment/create/CreateEnvironment.tsx
  src/components/ImportForm/ImportForm.tsx
  src/components/ImportForm/utils/auth-utils.ts
  src/components/ImportForm/utils/cdq-utils.ts
  src/components/NamespacedPage/NamespacedPage.tsx
  src/components/NamespacedPage/__tests__/NamespacedPage.spec.tsx
  src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
  src/hacbs/components/ImportForm/BuildSection.tsx
  src/hacbs/components/ImportForm/ImportForm.tsx
  src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/hacbs/components/PipelineRunListView/PipelineRunsListView.tsx
  src/hooks/index.ts
  src/hooks/useEnvironments.ts
  src/hooks/usePipelineRunsForApplication.ts
  src/utils/namespace-context-utils.ts
  src/utils/test-utils.tsx
Labels: lgtm, approved

#189 add hook to get and set a URL search param like useState
  src/hooks/__tests__/useSearchParam.spec.ts
  src/hooks/useSearchParam.ts
Labels: lgtm, approved

#186 HACBS: Adds unit tests for PLR list and details
  src/hacbs/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
  src/hacbs/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
Labels: lgtm, approved, hacbs

#190 Enable Pipelines as code in HACBS workflow
  src/components/ImportForm/utils/submit-utils.ts
  src/hacbs/components/ImportForm/BuildSection.tsx
  src/hacbs/components/ImportForm/__tests__/BuildSection.spec.tsx
  src/hacbs/components/ImportForm/utils/__tests__/submit-utils-spec.ts
  src/hacbs/components/ImportForm/utils/submit-utils.ts
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/hacbs/components/PipelineRunListView/PipelineRunListRow.tsx
  src/hacbs/components/PipelineRunListView/PipelineRunsListView.tsx
  src/hacbs/consts/pipelinerun.ts
  src/hacbs/hooks/useBuildPipelines.ts
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved, hacbs

#185 Add HAC BS integration tests tab for applications
  src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
  src/hacbs/components/ApplicationDetails/tabs/EnvironmentsTab.tsx
  src/hacbs/components/ApplicationDetails/tabs/IntegrationTestsTab.tsx
  src/hacbs/components/IntegrationTestsListView/IntegrationTestListHeader.ts
  src/hacbs/components/IntegrationTestsListView/IntegrationTestListRow.tsx
  src/hacbs/components/IntegrationTestsListView/IntegrationTestsListView.tsx
  src/hacbs/components/IntegrationTestsListView/__data__/mock-integration-tests.ts
  src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListRow.spec.tsx
  src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx
  src/hacbs/components/IntegrationTestsListView/useIntegrationTestActions.tsx
  src/hacbs/components/PipelineRunListView/PipelineRunListHeader.ts
Labels: lgtm, approved, hacbs

#193 wait for access check to have a status
  src/components/ImportForm/utils/__tests__/auth-utils.spec.ts
  src/components/ImportForm/utils/auth-utils.ts
Labels: lgtm, approved

#195 fix 'Go to application' from wizard
  src/hacbs/components/ImportForm/ImportForm.tsx
  src/hacbs/components/ImportForm/__tests__/ImportForm.spec.tsx
  src/hacbs/components/ImportForm/useImportSteps.tsx
  src/hacbs/components/ImportForm/utils/submit-utils.ts
Labels: lgtm, approved, hacbs

#179 Add modal to edit environment strategy
  src/components/Environment/EditStrategyModal.tsx
  src/components/Environment/__tests__/EditStrategyModal.spec.tsx
  src/components/Environment/environment-actions.ts
Labels: lgtm, approved

#171 Use feature flags for signup flow
  config/remotePlugin.js
  src/components/NamespacedPage/NamespacedPage.tsx
  src/components/NamespacedPage/__tests__/NamespacedPage.spec.tsx
  src/components/Signup/SignupView.tsx
  src/components/Signup/__tests__/SignupView.spec.tsx
  src/hooks/__tests__/useSignupStatus.spec.ts
  src/hooks/useSignupStatus.ts
  src/utils/__tests__/flag-utils.spec.ts
  src/utils/flag-utils.ts
Labels: lgtm, approved

#192 add help topic for settings page
  src/components/Environment/EnvironmentListView.tsx
  src/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/pages/WorkspaceSettingsPage.tsx
Labels: lgtm, approved

#175 Add application environment details view
  config/remotePlugin.js
  src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
  src/components/ApplicationDetailsView/ComponentListView.tsx
  src/components/ApplicationDetailsView/__tests__/ApplicationDetailsView.spec.tsx
  src/components/ApplicationEnvironment/ApplicationEnvironmentDetails.scss
  src/components/ApplicationEnvironment/ApplicationEnvironmentDetailsView.tsx
  src/components/ApplicationEnvironment/ApplicationEnvironmentGraphView.tsx
  src/components/ApplicationEnvironment/ApplicationEnvironmentListItem.scss
  src/components/ApplicationEnvironment/ApplicationEnvironmentListItem.tsx
  src/components/ApplicationEnvironment/ApplicationEnvironmentListView.tsx
  src/components/ApplicationEnvironment/ApplicationEnvironmentRevisionLink.tsx
  src/components/ApplicationEnvironment/ApplicationEnvironmentSidePanel.scss
  src/components/ApplicationEnvironment/ApplicationEnvironmentSidePanel.tsx
  src/components/ApplicationEnvironment/SidePanelActionMenu.tsx
  src/components/ApplicationEnvironment/__data__/mock-data.ts
  src/components/ApplicationEnvironment/__tests__/ApplicationEnvironmentDetailsView.spec.tsx
  src/components/ApplicationEnvironment/__tests__/ApplicationEnvironmentSidePanel.spec.tsx
  src/components/ApplicationEnvironment/topology/actions/contextMenuActions.tsx
  src/components/ApplicationEnvironment/topology/components/ActionsMenu.tsx
  src/components/ApplicationEnvironment/topology/components/ComponentNode.tsx
  src/components/ApplicationEnvironment/topology/factories/componentFactory.ts
  src/components/ApplicationEnvironment/topology/factories/layoutFactory.ts
  src/components/ApplicationListView/ApplicationListRow.tsx
  src/components/Environment/ApplicationEnvironmentCards.tsx
  src/components/LogViewer/BuildLogViewer.tsx
  src/hacbs/components/ImportForm/ImportForm.tsx
  src/hacbs/components/ImportForm/__tests__/ImportForm.spec.tsx
  src/hooks/index.ts
  src/hooks/useComponentPipelineRun.tsx
  src/hooks/useGitOpsDeploymentCR.ts
  src/pages/ApplicationDetailsPage.tsx
  src/pages/ApplicationEnvironmentDetailsPage.tsx
  src/pages/ApplicationsPage.tsx
  src/shared/components/action-menu/ActionMenuContent.tsx
  src/shared/utils/git-utils.tsx
  src/utils/environment-utils.ts
Labels: lgtm

#201 Update import wizard with step level title, description and help links
  src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
  src/components/ImportForm/utils/useImportSteps.tsx
  src/pages/ImportPage.tsx
Labels: lgtm, approved

#202 Set CDQ only for current source
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/utils/__tests__/cdq-utils.spec.ts
  src/components/ImportForm/utils/cdq-utils.ts
Labels: lgtm, approved

#200 fix workflow visualization with non existing parent environment
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/visualization-utils.spec.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts
Labels: lgtm, approved, hacbs

#188 add hacbs environments
  config/remotePlugin.js
  integration-tests/utils/Common.ts
  src/components/ApplicationDetailsView/ComponentListView.tsx
  src/components/ApplicationEnvironment/ApplicationEnvironmentDetailsView.tsx
  src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
  src/components/ComponentSettingsForm/ComponentSettingsView.tsx
  src/components/Environment/EnvironmentListView.tsx
  src/components/Environment/__tests__/EditStrategyModal.spec.tsx
  src/components/Environment/__tests__/EnvironmentCard.spec.tsx
  src/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/components/Environment/create/CreateEnvironment.tsx
  src/components/Environment/create/CreateEnvironmentForm.tsx
  src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx
  src/components/Environment/create/__tests__/ParentEnvironment.spec.tsx
  src/components/ImportForm/ImportForm.tsx
  src/hacbs/components/ApplicationDetails/DetailsPage.tsx
  src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
  src/hacbs/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
  src/hacbs/components/ApplicationDetails/__tests__/HacbsApplicationDetails.spec.tsx
  src/hacbs/components/ApplicationDetails/tabs/CommitsTab.tsx
  src/hacbs/components/ApplicationDetails/tabs/EnvironmentsTab.tsx
  src/hacbs/components/Environment/EnvironmentCard.tsx
  src/hacbs/components/Environment/EnvironmentListView.tsx
  src/hacbs/components/Environment/__tests__/EnvironmentCard.spec.tsx
  src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/hacbs/components/Environment/__tests__/utils.spec.ts
  src/hacbs/components/Environment/utils.ts
  src/hacbs/components/IntegrationTestsListView/IntegrationTestsListView.tsx
  src/hacbs/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunEnterpriseContractTab.tsx
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunEventsTab.tsx
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunYamlTab.tsx
  src/hacbs/components/PipelineRunListView/PipelineRunListRow.tsx
  src/hacbs/components/PipelineRunListView/PipelineRunsListView.tsx
  src/hacbs/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
  src/hacbs/pages/PipelineRunPage.tsx
  src/hooks/useSearchParam.ts
  src/pages/CreateEnvironmentPage.tsx
  src/pages/WorkspaceSettingsPage.tsx
  src/types/environment.ts
Labels: lgtm, approved, hacbs

#197 Add pipelinerun visualization in details page
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/WorkflowGraph.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/WorkflowVisualizationSurface.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/const.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/edges/WorkflowEdge.tsx
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/factories.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/draw-utils.ts
  src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts
  src/hacbs/components/PipelineRunDetailsView/PipelineRunVisualization.scss
  src/hacbs/components/PipelineRunDetailsView/PipelineRunVisualization.tsx
  src/hacbs/components/PipelineRunDetailsView/__tests__/PipelineVisualization.spec.tsx
  src/hacbs/components/PipelineRunDetailsView/factories.ts
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunTaskRunsTab.tsx
  src/hacbs/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
  src/hacbs/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunTaskRunsTab.spec.tsx
  src/hacbs/components/PipelineRunDetailsView/visualization/nodes/PipelineRunNode.tsx
  src/hacbs/components/PipelineRunDetailsView/visualization/types.ts
  src/hacbs/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts
  src/hacbs/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
  src/hacbs/components/TaskRunListView/TaskRunListView.tsx
  src/hacbs/components/topology/__tests__/topology-utils.spec.ts
  src/hacbs/components/topology/const.ts
  src/hacbs/components/topology/dag.ts
  src/hacbs/components/topology/factories/VisualizationFactory.tsx
  src/hacbs/components/topology/factories/__tests__/VisualizationFactory.spec.tsx
  src/hacbs/components/topology/factories/__tests__/layoutFactory.spec.ts
  src/hacbs/components/topology/factories/index.ts
  src/hacbs/components/topology/factories/layoutFactory.ts
  src/hacbs/components/topology/topology-utils.ts
  src/hacbs/components/topology/utils/__tests__/create-utils.spec.ts
  src/hacbs/components/topology/utils/create-utils.ts
Labels: lgtm, approved, hacbs

#207 fix useSearchParam using stale value with multiple update
  src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/hooks/__mocks__/useSearchParams.ts
  src/hooks/__tests__/useSearchParam.spec.ts
  src/hooks/useSearchParam.ts
  src/utils/test-utils.tsx
Labels: lgtm, approved

#194 Add ability to add an integration test to an application
  config/remotePlugin.js
  src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
  src/hacbs/components/ImportForm/useImportSteps.tsx
  src/hacbs/components/IntegrationTestForm/IntegrationTestForm.tsx
  src/hacbs/components/IntegrationTestForm/IntegrationTestSection.tsx
  src/hacbs/components/IntegrationTestForm/IntegrationTestView.tsx
  src/hacbs/components/IntegrationTestForm/__tests__/IntegrationTestSection.spec.tsx
  src/hacbs/components/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
  src/hacbs/components/IntegrationTestsListView/IntegrationTestsListView.tsx
  src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx
  src/hacbs/pages/IntegrationTestPage.tsx
Labels: lgtm, approved, hacbs
