Repository openshift/hac-dev, pull requests merged in 2023-08, with the labels that each got.

#722 add solution field to EC results expanded section
  src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractRow.tsx
  src/components/EnterpriseContractView/__data__/mockEnterpriseContractLogsJson.ts
  src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
  src/components/EnterpriseContractView/types.ts
  src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
Labels: lgtm, approved

#747 fix-commit-label-shortname
  src/components/Commits/__tests__/CommitsListRow.spec.tsx
  src/components/Commits/__tests__/CommitsListView.spec.tsx
  src/shared/components/commit-label/CommitLabel.tsx
  src/shared/components/commit-label/__tests__/CommitLabel.spec.tsx
Labels: lgtm, approved

#727 Switch to new build request system annotations
  helpers/resources/component.yaml
  helpers/setup.sh
  src/components/ApplicationDetails/__data__/WorkflowComponentsData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
  src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/node-utils.spec.ts
  src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
  src/components/Components/__data__/mock-data.ts
  src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx
  src/hooks/__tests__/usePACState.spec.ts
  src/hooks/usePACState.ts
  src/utils/__tests__/component-utils.spec.ts
  src/utils/__tests__/create-utils.spec.ts
  src/utils/component-utils.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#750 Update OWNERS
  OWNERS
  README.md
Labels: lgtm, approved

#745 Improve performance by batching tekton-results API requests in PLR list pages.
  src/components/Commits/tabs/CommitsPipelineRunTab.tsx
  src/components/PipelineRunListView/PipelineRunListRow.tsx
  src/components/PipelineRunListView/PipelineRunsListView.tsx
  src/consts/pipelinerun.ts
  src/hooks/__tests__/useScanResults.spec.ts
  src/hooks/useScanResults.ts
  src/hooks/useTektonResults.ts
  src/utils/__tests__/tekton-results.spec.ts
  src/utils/tekton-results.ts
Labels: lgtm, approved

#753 When build is triggered from main branch set BETA to true
  test.sh
Labels: approved

#755 Force beta build via hard coded deployment
  config/prod.webpack.config.js
  pr_check.sh
Labels: lgtm, approved

#758 reset active workspace before listing workspaces
  src/components/PipelineRunListView/PipelineRunListRow.tsx
  src/components/PipelineRunListView/__tests__/PipelineRunListRow.spec.tsx
  src/hooks/useScanResults.ts
  src/utils/workspace-context-utils.ts
Labels: lgtm, approved

#749 Update technologies in overview page
  src/components/Overview/AboutSection.tsx
  src/imgs/overview/Go.svg
  src/imgs/overview/Java.svg
Labels: lgtm, approved

#740 e2e update: add wait for page load after deleting IT test
  integration-tests/tests/advanced-happy-path.spec.ts
Labels: lgtm, approved

#759 Enable `(!)` cel filter in tekton results API
  src/utils/__tests__/tekton-results.spec.ts
  src/utils/tekton-results.ts
Labels: lgtm, approved

#760 e2e: Update advance flow pipelineruns Task names
  integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
  integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
Labels: lgtm, approved

#761 update TR Api query filter and page size in lifecycle graph
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppIntegrationTestNodes.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppBuildNodes.ts
  src/hooks/__tests__/useBuildPipelines.spec.ts
  src/hooks/useBuildPipelines.ts
  src/hooks/useTestPipelines.ts
Labels: lgtm, approved

#765 Fix create button flickering after component detection
  src/components/ImportForm/GitImportActions.tsx
Labels: lgtm, approved

#764 Add support for selecting components during import flow
  src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
  src/components/ImportForm/GitImportForm.tsx
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
  src/components/ImportForm/ReviewSection/__tests__/ReviewSection.spec.tsx
  src/components/ImportForm/utils/__tests__/submit-utils.spec.ts
  src/components/ImportForm/utils/__tests__/validation-utils.spec.ts
  src/components/ImportForm/utils/submit-utils.ts
  src/components/ImportForm/utils/types.ts
  src/components/ImportForm/utils/validation-utils.ts
Labels: lgtm, approved

#768 e2e: enterprise contract test update
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/basic-happy-path.spec.ts
  integration-tests/tests/environments-tests.spec.ts
Labels: lgtm, approved

#743 enable passing cypress args to image entrypoint
  integration-tests/Dockerfile
  integration-tests/README.md
  integration-tests/entrypoint.sh
Labels: lgtm, approved

#754 Show pending state for signup ProvisioningSpace status
  src/utils/__tests__/flag-utils.spec.ts
  src/utils/flag-utils.ts
  src/utils/signup-utils.ts
Labels: lgtm, approved

#752 Show PAC build errors
  src/components/Components/ComponentPACStateLabel.tsx
  src/components/CustomizedPipeline/CustomizePipelines.tsx
  src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx
  src/hooks/__tests__/usePACState.spec.ts
  src/hooks/usePACState.ts
Labels: lgtm, approved

#762 Fix namefilter in pipelinerun list page causing memory leaks
  src/components/PipelineRunListView/PipelineRunsListView.tsx
  src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
  src/hooks/useScanResults.ts
  src/hooks/useTektonResults.ts
  src/utils/__tests__/tekton-results.spec.ts
  src/utils/tekton-results.ts
Labels: lgtm, approved

#730 Always allow component creation if dockerfile runtime is selected
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
  src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
Labels: lgtm, approved

#772 make target port warning
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
Labels: lgtm, approved

#770 e2e: Remove the xpath plugin and update the tests
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/support/commands/index.ts
  integration-tests/support/pageObjects/global-po.ts
  integration-tests/tsconfig.json
  integration-tests/utils/UIhelper.ts
Labels: lgtm, approved

#741 Add check for all buttons to be ready.
  integration-tests/support/constants/PageTitle.ts
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/support/pages/GetStartedPage.ts
  integration-tests/utils/Login.ts
Labels: lgtm, approved

#773 fix vulnerability column not loading issue
  src/hooks/useScanResults.ts
Labels: lgtm, approved

#771 Add secrets list and delete action
  config/remotePlugin.js
  src/components/ImportForm/SecretSection/SecretSection.tsx
  src/components/Secrets/SecretForm.tsx
  src/components/Secrets/SecretModal.tsx
  src/components/Secrets/SecretTypeSelector.tsx
  src/components/Secrets/SecretsListView/SecretsList.tsx
  src/components/Secrets/SecretsListView/SecretsListHeader.tsx
  src/components/Secrets/SecretsListView/SecretsListRow.tsx
  src/components/Secrets/SecretsListView/SecretsListView.tsx
  src/components/Secrets/__tests___/SecretModal.spec.tsx
  src/components/Secrets/__tests___/SecretTypeSelector.spec.tsx
  src/components/Secrets/__tests___/SecretsListView.spec.tsx
  src/components/Secrets/__tests___/secret-data.ts
  src/components/Secrets/__tests___/secret-utils.spec.ts
  src/components/Secrets/secret-actions.ts
  src/components/Secrets/secret-modal.tsx
  src/components/Secrets/secret-utils.ts
  src/hooks/UseRemoteSecrets.ts
  src/models/index.ts
  src/models/remotesecret.ts
  src/pages/SecretsListPage.tsx
  src/pages/__tests__/SecretsListPage.spec.tsx
  src/types/secret.ts
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#746 Add snapshot details
  config/remotePlugin.js
  src/components/ApplicationDetails/__data__/WorkflowComponentsData.ts
  src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
  src/components/Commits/__data__/pipeline-with-commits.ts
  src/components/Components/__data__/mock-data.ts
  src/components/Environment/EnvironmentCard.tsx
  src/components/GitLink/GitRepoLink.tsx
  src/components/SnapshotDetails/SnapshotDetailsView.tsx
  src/components/SnapshotDetails/__tests__/SnapshotDetailsView.spec.tsx
  src/components/SnapshotDetails/tabs/SnapshotComponentsEmptyState.tsx
  src/components/SnapshotDetails/tabs/SnapshotComponentsList.tsx
  src/components/SnapshotDetails/tabs/SnapshotComponentsListHeader.tsx
  src/components/SnapshotDetails/tabs/SnapshotComponentsListRow.tsx
  src/components/SnapshotDetails/tabs/SnapshotOverview.tsx
  src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsEmptyState.spec.tsx
  src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsList.spec.tsx
  src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsListRow.spec.tsx
  src/components/SnapshotDetails/tabs/__tests__/SnapshotOverview.spec.tsx
  src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts
  src/pages/SnapshotDetailsPage.tsx
  src/pages/__tests__/SnapshotDetailsPage.spec.tsx
  src/types/coreBuildService.ts
Labels: lgtm, approved

#778 Add git ref and build context fields in review section of import
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
Labels: lgtm, approved

#777 e2e: PF5 upgrade fix
  integration-tests/support/pageObjects/global-po.ts
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/support/pages/EnvironmentsPage.ts
Labels: lgtm, approved

#781 e2e: deploy fewer dependencies with bonfire
  pr_check.sh
Labels: lgtm, ok-to-test, approved

#774 pact: add templates and use v3 API
  pact-tests/application-creation.pact.spec.ts
  pact-tests/contracts/application-service/create-application.ts
  pact-tests/contracts/application-service/get-application.ts
  pact-tests/contracts/contracts.ts
  pact-tests/get-application.pact.spec.ts
  pact-tests/pact-test-utils.ts
Labels: lgtm, approved

#784 e2e: Secrets validation and deletion using UI
  integration-tests/support/constants/PageTitle.ts
  integration-tests/support/pages/SecretsPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
Labels: lgtm, approved

#775 Add secret subforms component
  package-lock.json
  package.json
  src/components/Secrets/ImagePullSecretForm.tsx
  src/components/Secrets/KeyValueSecretForm.tsx
  src/components/Secrets/SecretTypeSubForm.tsx
  src/components/Secrets/SourceSecretForm.tsx
  src/components/Secrets/__tests___/ApplicationDropdown.spec.tsx
  src/components/Secrets/__tests___/ComponentDropdown.spec.tsx
  src/components/Secrets/__tests___/EncodedFileUploadField.spec.tsx
  src/components/Secrets/__tests___/EncodedInputField.spec.tsx
  src/components/Secrets/__tests___/EncodedKeyValueUploadField.spec.tsx
  src/components/Secrets/__tests___/EnvironmentDropdown.spec.tsx
  src/components/Secrets/__tests___/ImagePullSecretForm.spec.tsx
  src/components/Secrets/__tests___/MultiImageCredentialForm.spec.tsx
  src/components/Secrets/__tests___/SecretTypeSubForm.spec.tsx
  src/components/Secrets/__tests___/SourceSecretForm.spec.tsx
  src/components/Secrets/secret-utils.ts
  src/components/Secrets/utils/ApplicationDropdown.tsx
  src/components/Secrets/utils/ComponentDropdown.tsx
  src/components/Secrets/utils/EncodedFileUploadField.tsx
  src/components/Secrets/utils/EncodedInputField.tsx
  src/components/Secrets/utils/EncodedKeyValueUploadField.tsx
  src/components/Secrets/utils/EnvironmentDropdown.tsx
  src/components/Secrets/utils/MultiImageCredentialForm.tsx
  src/shared/components/dropdown/BasicDropdown.tsx
  src/shared/components/dropdown/index.ts
  src/shared/components/formik-fields/FileUploadField.tsx
  src/shared/components/formik-fields/InputField.tsx
  src/shared/components/formik-fields/field-types.ts
  src/shared/components/formik-fields/key-value-file-input-field/KeyValueFileInputField.tsx
  src/shared/components/pipeline-run-logs/logs/Logs.tsx
Labels: lgtm, approved
