Repository openshift/hac-dev, pull requests merged in 2023-09, with the labels that each got.

#785 use RemoteSecret for creating partner task secrets
  src/components/ComponentSettingsForm/__tests__/ComponentSettingsView.spec.tsx
  src/components/ImportForm/SecretSection/SecretSection.tsx
  src/shared/components/formik-fields/key-value-file-input-field/KeyValueFileInputField.tsx
  src/types/secret.ts
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#786 Update pact test doc for the new version
  pactTests.md
Labels: lgtm, approved

#791 Fix the broken style issue on local setup
  config/dev.webpack.config.js
Labels: lgtm, approved

#782 Update Edit component to Edit deployment settings
  config/remotePlugin.js
  integration-tests/support/constants/PageTitle.ts
  integration-tests/support/pageObjects/createApplication-po.ts
  integration-tests/support/pages/ApplicationDetailPage.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
  src/components/ApplicationDetails/component-actions.tsx
  src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
  src/components/Components/ComponentDetails/ComponentDetailsView.tsx
  src/components/Components/ComponentDetails/tabs/ComponentDetailsTab.tsx
  src/components/Components/__tests__/ComponentListItem.spec.tsx
  src/components/CustomizedPipeline/CustomizeComponentPipeline.tsx
  src/components/CustomizedPipeline/CustomizePipelines.tsx
  src/components/DeploymentSettingsForm/DeploymentSettingsForm.scss
  src/components/DeploymentSettingsForm/DeploymentSettingsForm.tsx
  src/components/DeploymentSettingsForm/DeploymentSettingsView.tsx
  src/components/DeploymentSettingsForm/__tests__/DeploymentSettingsView.spec.tsx
  src/components/ImportForm/ReviewSection/ComponentForm.tsx
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/pages/DeploymentSettingsPage.tsx
  src/pages/__tests__/DeploymentSettingsPage.spec.tsx
Labels: lgtm, approved

#790 Select first failed logs tab by default
  src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx
  src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx
Labels: lgtm, approved

#796 e2e: Component details automation
  integration-tests/support/pageObjects/global-po.ts
  integration-tests/support/pages/tabs/ComponentsTabPage.ts
  integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
  integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/basic-happy-path.spec.ts
  integration-tests/tests/environments-tests.spec.ts
  integration-tests/utils/Applications.ts
  integration-tests/utils/UIhelper.ts
Labels: lgtm, approved

#792 fix back and cancel action for git import form
  src/components/Environment/EditStrategyModal.tsx
  src/components/ImportForm/CloseImportFormModal.tsx
  src/components/modal/DeleteResourceModal.tsx
  src/components/modal/createModalLauncher.tsx
Labels: lgtm, approved

#716 Enable auth flow for private repo
  config/remotePlugin.js
  src/components/ImportForm/SourceSection/AuthOptions.tsx
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/ImportForm/SourceSection/__tests__/AuthOptions.spec.tsx
  src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
  src/components/ImportForm/SourceSection/useEnablePrivateAuthFlowFlag.ts
  src/components/ImportForm/utils/__tests__/auth-utils.spec.ts
  src/components/ImportForm/utils/auth-utils.ts
  src/utils/flag-utils.ts
Labels: lgtm, approved

#802 Fix component details when no container image
  src/components/Components/ComponentDetails/__tests__/ComponentDetails.spec.tsx
  src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx
Labels: lgtm, approved

#787 Add Deployments tab to the Component Details page
  src/components/Components/ComponentDeployments/ComponentDeploymentsListHeader.tsx
  src/components/Components/ComponentDeployments/ComponentDeploymentsListRow.scss
  src/components/Components/ComponentDeployments/ComponentDeploymentsListRow.tsx
  src/components/Components/ComponentDeployments/ComponentDeploymentsListView.tsx
  src/components/Components/ComponentDeployments/__tests__/ComponentDeploymentsListRow.spec.tsx
  src/components/Components/ComponentDetails/ComponentDetailsView.tsx
  src/components/Components/ComponentDetails/__data__/mockComponentDetails.ts
  src/components/Components/ComponentDetails/__tests__/ComponentActivityTab.spec.tsx
  src/components/Components/ComponentDetails/__tests__/ComponentDeploymentsTab.spec.tsx
  src/components/Components/ComponentDetails/tabs/ComponentActivityTab.tsx
  src/components/Components/ComponentDetails/tabs/ComponentDeploymentsTab.tsx
  src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx
  src/components/PodLogs/PodLogsButton.tsx
  src/hooks/useComponentDeployment.ts
  src/shared/components/table/Table.tsx
Labels: lgtm, approved

#803 Remove snapshot details action
  src/components/SnapshotDetails/SnapshotDetailsView.tsx
Labels: lgtm, approved

#806 e2e: fix getPipelineRunNameByLabel not waiting for the resource
  integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
Labels: lgtm, approved

#789 add Releaseplan, ReleasePlanAdmission, ReleaseStrategy list page
  config/remotePlugin.js
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
  src/components/PageAccess/PageAccessCheck.tsx
  src/components/PageAccess/__tests__/withPageAccessCheck.spec.tsx
  src/components/PageAccess/withPageAccessCheck.tsx
  src/components/ReleaseService/ReleasePlan/ReleasePlanListHeader.tsx
  src/components/ReleaseService/ReleasePlan/ReleasePlanListRow.tsx
  src/components/ReleaseService/ReleasePlan/ReleasePlanListView.tsx
  src/components/ReleaseService/ReleasePlan/__data__/release-plan.mock.ts
  src/components/ReleaseService/ReleasePlan/__tests__/ReleasePlanListRow.spec.tsx
  src/components/ReleaseService/ReleasePlan/__tests__/ReleasePlanListView.spec.tsx
  src/components/ReleaseService/ReleasePlan/releaseplan-actions.tsx
  src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListHeader.tsx
  src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListRow.tsx
  src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListView.tsx
  src/components/ReleaseService/ReleasePlanAdmission/__data__/release-plan-admission.mock.ts
  src/components/ReleaseService/ReleasePlanAdmission/__tests__/ReleasePlanAdmissionListRow.spec.tsx
  src/components/ReleaseService/ReleasePlanAdmission/__tests__/ReleasePlanAdmissionListView.spec.tsx
  src/components/ReleaseService/ReleasePlanAdmission/releaseplanadmission-actions.tsx
  src/components/ReleaseService/ReleaseService.tsx
  src/components/ReleaseService/ReleaseServiceEmptyState.tsx
  src/components/ReleaseService/ReleaseStrategy/ReleaseStrategyListHeader.tsx
  src/components/ReleaseService/ReleaseStrategy/ReleaseStrategyListRow.tsx
  src/components/ReleaseService/ReleaseStrategy/ReleaseStrategyListView.tsx
  src/components/ReleaseService/ReleaseStrategy/__data__/release-strategy.mock.ts
  src/components/ReleaseService/ReleaseStrategy/__tests__/ReleasePlanListRow.spec.tsx
  src/components/ReleaseService/ReleaseStrategy/__tests__/ReleasePlanListView.spec.tsx
  src/components/ReleaseService/ReleaseStrategy/releasestrategy-actions.tsx
  src/components/ReleaseService/__tests__/ReleaseService.spec.tsx
  src/hooks/useReleasePlanAdmissions.ts
  src/hooks/useReleaseStrategies.ts
  src/models/release-plan-admission.ts
  src/pages/ReleaseServicesListPage.tsx
  src/types/coreBuildService.ts
  src/types/release-plan-admission.ts
  src/types/release-strategy.ts
Labels: lgtm, approved

#807 Add parametrized statuses
  pact-tests/application-creation.pact.spec.ts
  pact-tests/contracts/application-service/create-application.ts
  pact-tests/contracts/application-service/get-application.ts
  pact-tests/contracts/application-service/state-params.ts
  pact-tests/get-application.pact.spec.ts
Labels: lgtm, approved

#811 e2e: enable snyk check
  integration-tests/cypress.config.ts
  integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/utils/Applications.ts
  pr_check.sh
Labels: lgtm, approved

#814 Fix integration name validation issue
  src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/validation-utils.spec.ts
  src/components/IntegrationTest/IntegrationTestForm/utils/validation-utils.ts
Labels: lgtm, approved

#813 fix app name auto recommendation when git url has extra spaces
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/components/ImportForm/utils/__tests__/useValidApplicationName.spec.ts
Labels: lgtm, approved

#809 chore: add commitlint to enforce conventional commit messages
  .commitlintrc.js
  .husky/commit-msg
  package-lock.json
  package.json
Labels: lgtm, approved

#810 Improve application overview screen
  integration-tests/support/pageObjects/createApplication-po.ts
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/tests/basic-happy-path.spec.ts
  src/components/Activity/ActivityTab.tsx
  src/components/ApplicationDetails/tabs/ApplicationOverviewTab.tsx
  src/components/ApplicationDetails/tabs/__tests__/__snapshots__/useWhatsNextItems.spec.ts.snap
  src/components/ApplicationDetails/tabs/overview/sections/AppWorkflowSection.tsx
  src/components/ApplicationDetails/tabs/useWhatsNextItems.ts
  src/components/Commits/CommitsListView.tsx
  src/components/Commits/__tests__/CommitsListView.spec.tsx
  src/components/Components/ComponentDeployments/ComponentDeploymentsListView.tsx
  src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestsListView.tsx
  src/components/IntegrationTest/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx
  src/components/PipelineRunListView/PipelineRunsListView.tsx
  src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
  src/components/WhatsNext/WhatsNextSection.tsx
  src/shared/components/status-box/StatusBox.tsx
  src/shared/components/table/Table.scss
  src/shared/components/table/Table.tsx
  src/shared/components/table/TableComponent.tsx
Labels: lgtm, approved

#812 Update computation of deployed application status
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/utils/Applications.ts
  src/components/ApplicationDetails/ApplicationHeader.tsx
  src/components/ApplicationDetails/__data__/WorkflowSnapshotsEnvironmentBindingsData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts
  src/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/hooks/__data__/mock-data.ts
  src/hooks/useApplicationHealthStatus.ts
  src/types/coreBuildService.ts
  src/utils/environment-utils.tsx
Labels: lgtm, approved

#818 chore: bootstrap releases for hac-dev
  .release-please-manifest.json
  release-please-config.json
Labels: lgtm, approved

#821 chore(main): release rhtap-ui 0.0.1
  .release-please-manifest.json
  CHANGELOG.md
  release-please-config.json
Labels: lgtm, approved, autorelease: pending

#822 Revert "chore(main): release rhtap-ui 0.0.1"
  .release-please-manifest.json
  CHANGELOG.md
  release-please-config.json
Labels: approved

#823 chore(main): release rhtap-ui 0.0.1
  .release-please-manifest.json
  CHANGELOG.md
  release-please-config.json
Labels: lgtm, approved, autorelease: pending
