Repository openshift/hac-dev, pull requests merged in 2023-10, with the labels that each got.

#824 Fix e2e Advanced flow
  integration-tests/tests/advanced-happy-path.spec.ts
Labels: lgtm, approved

#827 fix(test): wait for new github repo availability
  integration-tests/utils/APIHelper.ts
Labels: lgtm, approved

#795 feat: Add workspace sharing support
  config/remotePlugin.js
  src/components/ApplicationDetails/WorkspaceSwitcher.tsx
  src/components/ApplicationDetails/__tests__/WorkspaceSwitcher.spec.tsx
  src/components/ApplicationListView/__tests__/ApplicationListView.spec.tsx
  src/components/Components/ComponentDetails/__tests__/ComponentDetails.spec.tsx
  src/components/DeploymentSettingsForm/__tests__/DeploymentSettingsView.spec.tsx
  src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
  src/components/UserAccess/RevokeAccessModal.tsx
  src/components/UserAccess/SBRListHeader.tsx
  src/components/UserAccess/SBRListRow.tsx
  src/components/UserAccess/SBRStatusLabel.tsx
  src/components/UserAccess/UserAccessForm/PermissionsTable.scss
  src/components/UserAccess/UserAccessForm/PermissionsTable.tsx
  src/components/UserAccess/UserAccessForm/RoleSection.scss
  src/components/UserAccess/UserAccessForm/RoleSection.tsx
  src/components/UserAccess/UserAccessForm/UserAccessForm.tsx
  src/components/UserAccess/UserAccessForm/UserAccessFormPage.tsx
  src/components/UserAccess/UserAccessForm/UsernameSection.scss
  src/components/UserAccess/UserAccessForm/UsernameSection.tsx
  src/components/UserAccess/UserAccessForm/__tests__/PermissionsTable.spec.tsx
  src/components/UserAccess/UserAccessForm/__tests__/RoleSection.spec.tsx
  src/components/UserAccess/UserAccessForm/__tests__/UserAccessForm.spec.tsx
  src/components/UserAccess/UserAccessForm/__tests__/UsernameSection.spec.tsx
  src/components/UserAccess/UserAccessForm/__tests__/form-utils.spec.ts
  src/components/UserAccess/UserAccessForm/form-utils.ts
  src/components/UserAccess/UserAccessListView.tsx
  src/components/UserAccess/__tests__/RevokeAccessModal.spec.tsx
  src/components/UserAccess/__tests__/SBRListRow.spec.tsx
  src/components/UserAccess/__tests__/SBRStatusLabel.spec.tsx
  src/components/UserAccess/__tests__/UserAccessListView.spec.tsx
  src/components/UserAccess/__tests__/user-access-actions.spec.ts
  src/components/UserAccess/user-access-actions.ts
  src/components/modal/createModalLauncher.tsx
  src/hooks/__tests__/useWorkspaceForNamespace.spec.tsx
  src/hooks/useSpaceBindingRequests.ts
  src/models/index.ts
  src/models/space-binding-request.ts
  src/pages/EditAccessPage.tsx
  src/pages/GrantAccessPage.tsx
  src/pages/UserAccessPage.tsx
  src/pages/__tests__/DeploymentSettingsPage.spec.tsx
  src/pages/__tests__/EditAccessPage.spec.tsx
  src/pages/__tests__/UserAccessPage.spec.tsx
  src/types/index.ts
  src/types/space-binding-request.ts
  src/utils/__tests__/workspace-context-utils.spec.ts
  src/utils/breadcrumb-utils.tsx
  src/utils/test-utils.tsx
  src/utils/workspace-context-utils.ts
Labels: lgtm, approved

#799 feat(Integrationtest): integration test param support
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
  src/components/IntegrationTest/FormikParamsField.tsx
  src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx
  src/components/IntegrationTest/IntegrationTestForm/IntegrationTestView.tsx
  src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestSection.spec.tsx
  src/components/IntegrationTest/IntegrationTestForm/types.ts
  src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
  src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts
  src/components/IntegrationTest/__tests__/FormikParamsField.spec.tsx
  src/pages/EditIntegrationTestPage.tsx
  src/types/coreBuildService.ts
Labels: lgtm, approved

#829 refactor: list provider states in a separate place
  pact-tests/application-creation.pact.spec.ts
  pact-tests/contracts/application-service/create-application.ts
  pact-tests/contracts/application-service/get-application.ts
  pact-tests/get-application.pact.spec.ts
  pact-tests/states/state-params.ts
  pact-tests/states/states.ts
  pactTests.md
Labels: lgtm, approved

#828 feat: add kind annotation to EC ITS
  src/components/IntegrationTest/IntegrationTestForm/const.ts
  src/components/IntegrationTest/IntegrationTestForm/types.ts
  src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
  src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts
Labels: lgtm, ok-to-test, approved

#826 fix(task logs): show logs for skipped or idle tasks if they exist
  src/components/TaskRuns/TaskRunLogs.tsx
Labels: lgtm, approved

#832 fix(test): update pipeline labels
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/basic-happy-path.spec.ts
Labels: lgtm, approved

#817 fix: Use exact label match for PAC state check
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
  src/utils/__tests__/component-utils.spec.ts
  src/utils/component-utils.ts
Labels: lgtm, approved

#830 fix(path-description): modify the integration test path description
  src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx
Labels: lgtm, approved

#825 fix(overview graph): navigate to components list on No builds node click
  src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/node-utils.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
Labels: lgtm, approved

#805 feat(import flow): add visibility annotation on component creation
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/ImportForm/utils/submit-utils.ts
  src/components/ImportForm/utils/types.ts
Labels: lgtm, approved

#834 fix(int-filter): modify integration test search filter field
  src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestsListView.tsx
Labels: lgtm, approved

#816 feat( Integration test): edit params in details section
  src/components/IntegrationTest/EditParamsModal.tsx
  src/components/IntegrationTest/FormikParamsField.tsx
  src/components/IntegrationTest/IntegrationTestsListView/__data__/mock-integration-tests.ts
  src/components/IntegrationTest/__tests__/EditParamsModal.spec.tsx
  src/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx
  src/components/IntegrationTest/tabs/__tests__/IntegrationTestOverviewTab.spec.tsx
Labels: lgtm, approved

#835 fix(add-snpshot-link): add snapshot link in pipelinerun details page
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
Labels: lgtm, approved

#831 fix(releases): Enable filtering & sorting on Releases list view
  src/components/Filter/FilterToolbar.tsx
  src/components/Filter/__tests__/FilterToolbar.spec.tsx
  src/components/Releases/ReleasesListHeader.tsx
  src/components/Releases/ReleasesListRow.tsx
  src/components/Releases/ReleasesListView.tsx
  src/components/Releases/__data__/mock-release-data.ts
  src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx
  src/components/Releases/__tests__/ReleasesListRow.spec.tsx
  src/components/Releases/__tests__/ReleasesListView.spec.tsx
  src/hooks/useSortedResources.ts
  src/shared/components/table/Table.tsx
  src/shared/components/table/__tests__/Table.spec.tsx
Labels: lgtm, approved

#833 chore: remove cypress manual cookie preservation
  integration-tests/cypress.config.ts
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/support/commands/hooks.ts
Labels: lgtm, approved

#840 Remove caddy file in favor of universal build
  Caddyfile
  build_deploy.sh
  pr_check.sh
Labels: lgtm, approved

#841 fix(secret-list): fix secret list page error when secret is missing status field
  src/components/Secrets/__tests___/secret-utils.spec.ts
  src/components/Secrets/utils/secret-utils.ts
Labels: lgtm, approved

#842 chore(main): release rhtap-ui 0.1.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: lgtm, approved, autorelease: pending

#836 fix(application list): make delete application consistent
  integration-tests/support/pageObjects/global-po.ts
  src/components/ApplicationListView/application-actions.ts
Labels: lgtm, approved

#844 Revert "Remove caddy file in favor of universal build"
  Caddyfile
  build_deploy.sh
  pr_check.sh
Labels: lgtm, approved

#815 feat(components): update components list view
  integration-tests/support/pages/ApplicationDetailPage.ts
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/support/pages/tabs/ComponentsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/basic-happy-path.spec.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
  src/components/Components/BuildStatusColumn.tsx
  src/components/Components/ComponentDetails/ComponentDetailsView.tsx
  src/components/Components/ComponentDetails/tabs/ComponentBuildSettings.tsx
  src/components/Components/ComponentListItem.scss
  src/components/Components/ComponentListItem.tsx
  src/components/Components/ComponentListView.scss
  src/components/Components/ComponentListView.tsx
  src/components/Components/ComponentPACStateLabel.tsx
  src/components/Components/ComponentsFilterToolbarGroups.tsx
  src/components/Components/ComponentsListHeader.tsx
  src/components/Components/ComponentsListRow.tsx
  src/components/Components/ComponentsToolbar.tsx
  src/components/Components/__tests__/BuildStatusColumn.spec.tsx
  src/components/Components/__tests__/ComponentListItem.spec.tsx
  src/components/Components/__tests__/ComponentListView.spec.tsx
  src/hooks/__tests__/usePACStatesForComponents.spec.ts
  src/hooks/usePACState.ts
  src/hooks/usePACStatesForComponents.ts
  src/shared/components/pipeline-run-status/PipelineRunStatus.tsx
  src/shared/components/table/TableComponent.tsx
  src/utils/gitops-utils.tsx
Labels: lgtm, approved

#845 Turn on universal build
  Caddyfile
  build_deploy.sh
  pr_check.sh
  test.sh
Labels: lgtm, approved

#839 fix(Custom-build-pipeline-dialog): update text for custom build pipeline
  src/components/CustomizedPipeline/CustomizePipelines.tsx
Labels: lgtm, approved

#838 fix(access): Use username API to validate usernames in access form
  src/components/UserAccess/UserAccessForm/UsernameSection.tsx
  src/components/UserAccess/UserAccessForm/__tests__/UsernameSection.spec.tsx
  src/components/UserAccess/UserAccessForm/__tests__/form-utils.spec.ts
  src/components/UserAccess/UserAccessForm/form-utils.ts
Labels: lgtm, approved

#846 fix commit activity tab in components details page
  src/hooks/__tests__/useComponents.spec.ts
  src/hooks/useComponents.ts
Labels: lgtm, approved
