Repository openshift/hac-dev, pull requests merged in 2023-04, with the labels that each got.

#542 e2e test: Verify recent commits section on application overview page
  integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/utils/UIhelper.ts
Labels: lgtm, approved

#539 enable all what's next help topics at once
  src/components/HelpTopicLink/HelpTopicLink.tsx
  src/components/HelpTopicLink/__tests__/HelpTopicLink.spec.tsx
Labels: lgtm, approved

#534 Fix the link on integration test node in lifecycle visualization
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
Labels: lgtm, approved

#543 Use default image when runtime is not detected
  src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
Labels: lgtm, approved

#533 include annotation for component creation to new quay repo
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#544 add help text to dockerfile path field
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
Labels: lgtm, approved

#526 Add CommitLabel for displaying Commit IDs
  src/components/Commits/CommitDetailsView.tsx
  src/components/Commits/CommitsListHeader.tsx
  src/components/Commits/CommitsListRow.tsx
  src/shared/components/commit-label/CommitLabel.tsx
  src/shared/components/commit-label/__tests__/CommitLabel.spec.tsx
Labels: lgtm, approved

#520 UI treatment for displaying Application repositories
  package-lock.json
  package.json
  src/components/Components/ComponentListItem.tsx
  src/components/Components/__tests__/ComponentListItem.spec.tsx
  src/components/CustomizedPipeline/CustomizePipelines.tsx
  src/components/GitLink/GitRepoLink.tsx
  src/components/GitLink/__tests__/GitRepoLink.spec.tsx
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/shared/components/links/ExternalLink.tsx
  src/utils/__tests__/git-utils.spec.tsx
  src/utils/git-utils.tsx
Labels: lgtm, approved

#540 update integration test name validation message
  src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/validation-utils.spec.ts
  src/components/IntegrationTest/IntegrationTestForm/utils/validation-utils.ts
Labels: lgtm, approved

#547 e2e test: Update Commit details UI changes
  integration-tests/cypress.config.ts
  integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
  integration-tests/tests/create-application-from-private-git-form.spec.ts
  integration-tests/tests/create-application-from-private-git-source.spec.ts
Labels: lgtm, approved

#513 Add side panels for commit pipeline visualization
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNode.scss
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
  src/components/Commits/CommitDetails/CommitDetailsSidePanel.tsx
  src/components/Commits/CommitDetails/CommitDetailsView.scss
  src/components/Commits/CommitDetails/CommitDetailsView.tsx
  src/components/Commits/CommitDetails/__tests__/CommitDetailsView.spec.tsx
  src/components/Commits/CommitDetails/sidepanels/BuildSidePanel.tsx
  src/components/Commits/CommitDetails/sidepanels/CommitSidePanel.tsx
  src/components/Commits/CommitDetails/sidepanels/CommitWorkflowSidePanel.scss
  src/components/Commits/CommitDetails/sidepanels/CommitWorkflowSidePanel.tsx
  src/components/Commits/CommitDetails/sidepanels/EnvironmentSidePanel.tsx
  src/components/Commits/CommitDetails/sidepanels/IntegrationTestSidePanel.tsx
  src/components/Commits/CommitDetails/sidepanels/ManagedEnvironmentSidePanel.tsx
  src/components/Commits/CommitDetails/sidepanels/ReleaseSidePanel.tsx
  src/components/Commits/CommitDetails/sidepanels/__tests__/CommitSidePanels.spec.tsx
  src/components/Commits/CommitDetails/visualization/CommitComponentFactory.tsx
  src/components/Commits/CommitDetails/visualization/CommitVisualization.scss
  src/components/Commits/CommitDetails/visualization/CommitVisualization.tsx
  src/components/Commits/CommitDetails/visualization/CommitWorkflowNode.scss
  src/components/Commits/CommitDetails/visualization/CommitWorkflowNode.tsx
  src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
  src/components/Commits/CommitDetails/visualization/__tests__/CommitVisualization.spec.tsx
  src/components/Commits/CommitDetails/visualization/__tests__/commit-visualization-utils.spec.ts
  src/components/Commits/CommitDetails/visualization/commit-visualization-types.ts
  src/components/Commits/CommitDetails/visualization/commit-visualization-utils.tsx
  src/components/Commits/CommitDetails/visualization/useCommitWorkflowData.ts
  src/components/Commits/CommitDetailsView.tsx
  src/components/Commits/tabs/CommitDetails/CommitVisualization.scss
  src/components/Commits/tabs/CommitDetails/CommitVisualization.tsx
  src/components/Commits/tabs/CommitDetails/__tests__/CommitVisualization.spec.tsx
  src/components/Commits/tabs/CommitOverviewTab.tsx
  src/components/Commits/tabs/CommitsOverviewTab.tsx
  src/components/Environment/EnvironmentListView.tsx
  src/components/PipelineRunDetailsView/sidepanels/TaskRunDetails.tsx
  src/components/PipelineRunDetailsView/tabs/RunResultsList.scss
  src/components/PipelineRunDetailsView/tabs/RunResultsList.tsx
  src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
  src/components/SidePanel/SidePanel.tsx
  src/components/SidePanel/SidePanelContext.ts
  src/components/SidePanel/SidePanelHost.tsx
  src/hacbs/components/Environment/EnvironmentCard.tsx
  src/pages/CommitsPage.tsx
  src/pages/__tests__/CommitsPage.spec.tsx
  src/utils/commits-utils.ts
  src/utils/environment-utils.tsx
  src/utils/pipeline-utils.ts
Labels: lgtm, approved

#530 add table view for the enterprise contract results
  src/components/ApplicationDetails/__data__/WorkflowTestPipelinesData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.scss
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
  src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractRow.tsx
  src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractTable.tsx
  src/components/EnterpriseContractView/EnterpriseContractTable/__tests__/EnterpriseContractRow.spec.tsx
  src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
  src/components/EnterpriseContractView/__data__/mockEnterpriseContractLogsJson.ts
  src/components/EnterpriseContractView/__tests__/SecurityEnterpriseContractTab.spec.tsx
  src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
  src/components/EnterpriseContractView/types.ts
  src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
  src/components/EnterpriseContractView/utils.ts
  src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/components/TaskRunDetailsView/TaskRunDetailsView.tsx
Labels: lgtm, approved

#546 User provided component name should not be overridden by cdq defaults
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
  src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
  src/components/ImportForm/utils/__tests__/transform-utils.spec.ts
  src/components/ImportForm/utils/transform-utils.ts
  src/components/ImportForm/utils/types.ts
  src/shared/components/formik-fields/EditableLabelField.tsx
  src/shared/components/formik-fields/__tests__/EditableLabelField.spec.tsx
Labels: lgtm, approved

#541 limit port input value
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/shared/components/formik-fields/BaseInputField.tsx
  src/shared/components/formik-fields/InputField.tsx
Labels: lgtm, approved

#545 Avoid toggling menu open state on outside menu click handler
  src/shared/components/action-menu/ActionMenuToggle.tsx
  src/shared/components/action-menu/__tests__/ActionMenu.spec.tsx
Labels: lgtm, approved

#550 Update task name for scraping EC report output
  src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
  src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
Labels: lgtm, ok-to-test, approved

#548 Added Option to run all e2e test suite on pr check
  integration-tests/cypress.config.ts
  pr_check.sh
Labels: lgtm, approved

#503 Introducing pact test
  .gitignore
  package-lock.json
  package.json
  pact-tests/application-creation.pact.spec.ts
  pact-tests/get-application.pact.spec.ts
  pact-tests/matchers.ts
  pact-tests/pact-test-utils.ts
Labels: lgtm, approved

#549 remove component integration tests nodes in overview and commit visualization
  src/components/ApplicationDetails/tabs/overview/sections/__tests__/AppWorkflowSection.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppIntegrationTestNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useCommitWorkflowData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/types.ts
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-icon-utils.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
  src/components/Commits/CommitDetails/sidepanels/CommitWorkflowSidePanel.tsx
  src/components/Commits/CommitDetails/visualization/commit-visualization-types.ts
  src/components/Commits/CommitDetails/visualization/commit-visualization-utils.tsx
  src/components/Commits/CommitDetails/visualization/useCommitWorkflowData.ts
Labels: lgtm, approved

#551 consistent capitalization (in-app) of "Enterprise Contract"
  src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
  src/components/Modals/GettingStartedModal.tsx
  src/hacbs/components/WorkspaceSettings/WorkspaceSettings.tsx
Labels: lgtm, approved

#552 e2e test: Update Commit details UI changes
  integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
Labels: lgtm, approved

#557 Move sample card onlick handler to galleryitem
  src/components/ImportForm/SampleSection/SampleSection.tsx
Labels: lgtm, approved

#560 update label to identify enterprise-contract pipeline run
  src/components/EnterpriseContractView/utils.ts
Labels: lgtm, approved

#559 e2e test: Added 'Integration tests' test case
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/support/pages/AddIntegrationTestPage.ts
  integration-tests/support/pages/tabs/IntegrationTestsTabPage.ts
  integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/utils/Applications.ts
  integration-tests/utils/UIhelper.ts
Labels: lgtm, approved

#538 Pod logs
  src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx
  src/components/Components/BuildStatusColumn.tsx
  src/components/Components/ComponentListItem.tsx
  src/components/Components/ComponentListView.tsx
  src/components/Components/__tests__/BuildStatusColumn.spec.tsx
  src/components/Components/__tests__/ComponentListItem.spec.tsx
  src/components/Components/__tests__/ComponentListView.spec.tsx
  src/components/LogViewer/BuildLogViewer.tsx
  src/components/PodLogs/ContainerNavList.tsx
  src/components/PodLogs/PodLogViewer.tsx
  src/components/PodLogs/PodLogsColumn.tsx
  src/components/PodLogs/PodLogsViewer.scss
  src/components/PodLogs/__data__/pod-mock-data.ts
  src/components/PodLogs/__tests__/PodLogViewer.spec.tsx
  src/components/PodLogs/__tests__/PodLogsColumn.spec.tsx
  src/components/PodLogs/__tests__/pod-log-utils.spec.ts
  src/components/PodLogs/utils/pod-log-utils.ts
  src/hooks/__tests__/useGitOpsDeploymentCR.spec.ts
  src/hooks/useGitOpsDeploymentCR.ts
  src/models/deployment.ts
  src/shared/components/types.ts
  src/types/deployment.ts
  src/types/gitops-deployment.ts
Labels: lgtm, approved

#566 add clair scan documentation link in popover
  src/components/PipelineRunDetailsView/tabs/ClairScanDescriptionListGroup.tsx
Labels: lgtm, approved

#564 Fix width of visualization nodes based on labels
  package-lock.json
  package.json
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
Labels: lgtm, approved

#558 Set scrollbar on tasks list in build logs modal
  src/components/LogViewer/BuildLogViewer.scss
  src/components/LogViewer/BuildLogViewer.tsx
  src/shared/components/pipeline-run-logs/PipelineRunLogs.scss
  src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx
  src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx
Labels: lgtm, approved

#561 fix typo in enterprise contract security tab
  src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
  src/components/EnterpriseContractView/__tests__/SecurityEnterpriseContractTab.spec.tsx
Labels: lgtm, approved

#570 update component git repo links to include revision and context
  src/components/Components/ComponentListItem.tsx
  src/components/CustomizedPipeline/CustomizePipelines.tsx
  src/components/GitLink/GitRepoLink.tsx
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/utils/__tests__/git-utils.spec.tsx
  src/utils/git-utils.tsx
Labels: lgtm, approved

#569 Refactor pipeline run visualization
  src/components/Activity/ActivityTab.tsx
  src/components/Activity/__tests__/ActivityTab.spec.tsx
  src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useCommitWorkflowData.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useCommitWorkflowData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/visualization-utils.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts
  src/components/Commits/CommitDetails/visualization/useCommitWorkflowData.ts
  src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/components/PipelineRunDetailsView/PipelineRunVisualization.tsx
  src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
  src/components/PipelineRunDetailsView/__tests__/PipelineVisualization.spec.tsx
  src/components/PipelineRunDetailsView/factories.ts
  src/components/PipelineRunDetailsView/sidepanels/TaskRunPanel.tsx
  src/components/PipelineRunDetailsView/tabs/PipelineRunEventsTab.tsx
  src/components/PipelineRunDetailsView/tabs/PipelineRunYamlTab.tsx
  src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
  src/components/topology/__tests__/dag.spec.ts
  src/components/topology/dag.ts
  src/components/topology/factories/__tests__/VisualizationFactory.spec.tsx
Labels: lgtm, approved

#568 e2e: delete applications using api
  integration-tests/Dockerfile
  integration-tests/tests/create-application-from-private-git-form.spec.ts
  integration-tests/tests/create-application-from-private-git-source.spec.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
  integration-tests/tests/create-application-from-sample.spec.ts
  integration-tests/utils/Applications.ts
Labels: lgtm, approved

#565 fix build logs autoscroll performance issue
  src/shared/components/pipeline-run-logs/__tests__/Logs.spec.tsx
  src/shared/components/pipeline-run-logs/__tests__/MultiStreamLogs.spec.tsx
  src/shared/components/pipeline-run-logs/logs/Logs.tsx
  src/shared/components/pipeline-run-logs/logs/MultiStreamLogs.tsx
Labels: lgtm, approved

#555 Update create environment form
  package-lock.json
  package.json
  src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
  src/components/Environment/create/CreateEnvironment.tsx
  src/components/Environment/create/CreateEnvironmentForm.tsx
  src/components/Environment/create/KubeconfigUploadField.tsx
  src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx
  src/components/Environment/create/__tests__/KubeconfigUploadField.spec.tsx
  src/components/Environment/environment-utils.ts
  src/models/index.ts
  src/models/secret.ts
  src/shared/components/formik-fields/FileUploadField.tsx
  src/types/environment.ts
  src/types/index.ts
  src/types/secret.ts
Labels: lgtm, approved

#575 e2e: Integration tests pipeline runs details validation test
  integration-tests/support/pageObjects/global-po.ts
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/utils/Applications.ts
Labels: lgtm, approved

#576 e2e: test Update with GH reference and context dir validation
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
Labels: lgtm, approved

#578 e2e: fetch file contents from git instead of hardcoding
  integration-tests/tests/advanced-happy-path.spec.ts
Labels: lgtm, approved

#581 mochawesome html report for e2e tests
  integration-tests/cypress.config.ts
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/support/commands/index.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
Labels: lgtm, approved

#579 RHCLOUD-25402: Update CI/CD to Red Hat Trusted Application Pipeline
  integration-tests/support/constants/PageTitle.ts
  integration-tests/tests/basic-happy-path.spec.ts
  integration-tests/utils/Applications.ts
  src/components/ApplicationDetails/DetailsPage.tsx
  src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
  src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/Overview/IntroBanner.tsx
  src/consts/labels.ts
  src/pages/ApplicationsPage.tsx
  src/pages/ComponentSettingsPage.tsx
  src/pages/EnvironmentsListPage.tsx
  src/pages/OverviewPage.tsx
Labels: lgtm, approved, jira/valid-reference

#583 Enable TLS in caddy file
  Caddyfile
Labels: lgtm, approved

#584 Add view sbom link in pipelinerun details page
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
  src/components/topology/__data__/pipeline-test-data.ts
  src/utils/pipeline-utils.ts
Labels: lgtm, approved

#577 Check taskrun status when displaying logs
  src/components/NamespacedPage/NamespacedPage.tsx
  src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx
Labels: lgtm, approved

#586 Fix managed environment health status in environment card
  src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts
Labels: lgtm, approved

#588 Add ingressDomain for env create of non-OpenShift
  src/components/Environment/create/CreateEnvironment.tsx
  src/components/Environment/create/CreateEnvironmentForm.tsx
  src/components/Environment/create/IngressDomainField.tsx
  src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx
  src/components/Environment/environment-utils.ts
  src/components/ImportForm/utils/validation-utils.ts
Labels: lgtm, approved

#587 e2e: View pod log test case
  integration-tests/support/pageObjects/createApplication-po.ts
  integration-tests/support/pages/ApplicationDetailPage.ts
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/create-application-from-private-git-form.spec.ts
  integration-tests/tests/create-application-from-private-git-source.spec.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
  integration-tests/tests/create-application-from-sample.spec.ts
  integration-tests/utils/Applications.ts
Labels: lgtm, approved

#582 enterprise contract enhancements
  src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractRow.tsx
  src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractTable.tsx
  src/components/EnterpriseContractView/EnterpriseContractTable/__tests__/EnterpriseContractRow.spec.tsx
  src/components/EnterpriseContractView/EnterpriseContractTable/__tests__/EnterpriseContractTable.spec.tsx
  src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
  src/components/EnterpriseContractView/__data__/mockEnterpriseContractLogsJson.ts
  src/components/EnterpriseContractView/__tests__/SecurityEnterpriseContractTab.spec.tsx
  src/components/EnterpriseContractView/types.ts
  src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
  src/components/EnterpriseContractView/utils.ts
  src/components/EnterpriseContractView/utils.tsx
Labels: lgtm, approved

#589 Use TEST_OUTPUT task definition for task result status
  src/components/ApplicationDetails/__data__/WorkflowTestPipelinesData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/test-pipeline-data.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
  src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
  src/components/CustomizedPipeline/pr.yaml
  src/components/EnterpriseContractView/__data__/mockEnterpriseContractPolicies.ts
  src/components/PipelineRunDetailsView/__data__/mockVisualizationData.ts
  src/components/PipelineRunDetailsView/__tests__/PipelineVisualization.spec.tsx
  src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
  src/components/topology/__data__/pipeline-test-data.ts
  src/utils/pipeline-utils.ts
Labels: lgtm, approved

#593 change width for message and component column for enterprise contract table
  src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractTable.tsx
Labels: lgtm, approved
