Repository openshift/hac-dev, pull requests merged in 2023-01, with the labels that each got.

#296 feature flag and remove settings page for mvp
  config/remotePlugin.js
  src/utils/flag-utils.ts
Labels: lgtm, approved

#300 Update application name field to only show placeholder text
  src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
  src/components/ImportForm/ImportForm.tsx
Labels: lgtm, approved

#297 Remove redundant action menu items from application details
  src/components/ApplicationDetails/ApplicationDetails.tsx
Labels: lgtm, approved

#301 Updated font weight style for review component card link
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/shared/components/links/ExternalLink.tsx
Labels: lgtm, approved

#293 Add cancelling status for pipelineruns
  src/__data__/pipelinerun-data.ts
  src/shared/components/pipeline-run-logs/StatusIcon.tsx
  src/shared/components/pipeline-run-logs/__tests__/utils.spec.ts
  src/shared/components/pipeline-run-logs/utils.ts
Labels: lgtm, approved

#289 add Context Switcher to Application details view
  src/components/ApplicationDetails/ApplicationDetails.tsx
  src/components/ApplicationDetails/DetailsPage.tsx
  src/components/ApplicationDetailsView/ApplicationSwitcher.tsx
Labels: lgtm

#299 Update delete resource modal texts
  src/components/modal/DeleteResourceModal.tsx
  src/components/modal/resource-modals.tsx
Labels: lgtm, approved

#303 add learn more missing icon in component step
  src/components/ImportForm/SourceSection/SourceSection.tsx
Labels: lgtm, approved

#304 add breadcrumb for component
  src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
Labels: lgtm, approved

#295 Show commit status in commit list row
  src/components/Commits/CommitDetailsView.tsx
  src/components/Commits/CommitSidePanelHeader.tsx
  src/components/Commits/CommitsListRow.tsx
  src/components/Commits/__data__/pipeline-with-commits.ts
  src/components/Commits/__tests__/CommitsListRow.spec.tsx
  src/components/Commits/__tests__/CommitsListView.spec.tsx
  src/components/Commits/__tests__/commit-status.spec.ts
  src/components/Commits/commit-status.ts
Labels: lgtm, approved

#315 add karthik to OWNERS as an approver
  OWNERS
Labels: lgtm, approved

#311 Add sample info alert to visually highlight start with samples flow
  src/components/ImportForm/SampleSection/SampleInfoAlert.tsx
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
Labels: lgtm, approved

#314 Hide integration tests tab, nodes in the graph for mvp
  src/components/ApplicationDetails/ApplicationDetails.tsx
  src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useCommitWorkflowData.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useCommitWorkflowData.ts
Labels: lgtm, approved

#305 Update hac ui tests
  integration-tests/support/commands/hooks.ts
  integration-tests/support/pageObjects/createApplication-po.ts
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/support/pages/AddComponentPage.ts
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/tests/add-component-to-application.spec.ts
  integration-tests/tests/create-application-from-private-git-form.spec.ts
  integration-tests/tests/create-application-from-private-git-source.spec.ts
  integration-tests/tests/create-application-from-private-quay-image.spec.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
  integration-tests/tests/create-application-from-public-quay-image.spec.ts
  integration-tests/tests/create-application-from-sample.spec.ts
  src/components/ComponentsListView/ComponentListItem.tsx
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
Labels: lgtm

#323 Enable caddy config file so we can have better metrics
  Caddyfile
  nginx.conf
Labels: lgtm, approved

#327 Revert "Enable caddy config file so we can have better metrics"
  Caddyfile
  nginx.conf
Labels: approved

#318 update Environment subtitle copy
  src/hacbs/components/Environment/EnvironmentListView.tsx
  src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
Labels: lgtm, approved

#319 Remove learn more link from app overview and components tab
  src/components/ApplicationDetails/tabs/overview/sections/AppWorkflowSection.tsx
  src/components/Components/ComponentListView.tsx
Labels: lgtm, approved

#316 Run detection for samples after submit
  src/components/ImportForm/ImportForm.tsx
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx
  src/components/ImportForm/utils/__tests__/cdq-utils.spec.ts
  src/components/ImportForm/utils/__tests__/submit-utils.spec.ts
  src/components/ImportForm/utils/__tests__/transform-utils.spec.ts
  src/components/ImportForm/utils/__tests__/useImportSteps.spec.ts
  src/components/ImportForm/utils/cdq-utils.ts
  src/components/ImportForm/utils/submit-utils.ts
  src/components/ImportForm/utils/transform-utils.ts
  src/components/ImportForm/utils/types.ts
  src/components/ImportForm/utils/useImportSteps.tsx
  src/components/ImportForm/utils/validation-utils.ts
  src/types/component-detection-query.ts
Labels: lgtm, approved

#320 View pull request link should redirect to open pull requests page
  src/components/Components/BuildStatusColumn.tsx
Labels: lgtm, approved

#317 fix merge build pr status in component list view
  src/components/Components/BuildStatusColumn.tsx
  src/components/Components/__tests__/BuildStatusColumn.spec.tsx
  src/components/ComponentsListView/BuildStatusColumn.tsx
Labels: lgtm, approved

#313 Fix related pipelineruns field and add links to the related pipelineruns
  src/components/PipelineRunDetailsView/RelatedPipelineRuns.tsx
  src/components/PipelineRunDetailsView/visualization/utils/__tests__/RelatedPipelineRuns.spec.tsx
Labels: lgtm, approved

#321 Fix skipped task icon in pipelinerun visualization
  src/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts
  src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
Labels: lgtm, approved

#325 Use PF pipelines statusIcon component for icon consistency in plr logs and graph
  src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
  src/shared/components/pipeline-run-logs/StatusIcon.scss
  src/shared/components/pipeline-run-logs/StatusIcon.tsx
  src/shared/components/pipeline-run-logs/__tests__/utils.spec.ts
  src/shared/components/pipeline-run-logs/utils.ts
Labels: lgtm, approved

#308 Use path params instead of query params in details page tabs
  config/remotePlugin.js
  src/components/ApplicationDetails/ApplicationDetails.tsx
  src/components/ApplicationDetails/DetailsPage.tsx
  src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx
  src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
  src/components/ApplicationDetails/tabs/CommitsTab.tsx
  src/components/ApplicationDetails/tabs/overview/sections/__tests__/AppWorkflowSection.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppBuildNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppComponentsNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppIntegrationTestNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppReleaseNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppReleasePlanNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNode.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/types.ts
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
  src/components/Commits/AppRecentCommits.tsx
  src/components/Commits/CommitDetailsView.tsx
  src/components/Commits/CommitsListView.tsx
  src/components/Commits/__tests__/CommitDetailsView.spec.tsx
  src/components/Commits/tabs/__tests__/CommitsPipelineRunTab.spec.tsx
  src/components/IntegrationTest/IntegrationTestDetailsView.tsx
  src/components/IntegrationTest/IntegrationTestForm/IntegrationTestForm.tsx
  src/components/IntegrationTest/IntegrationTestForm/IntegrationTestView.tsx
  src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
  src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestListRow.tsx
  src/components/IntegrationTest/__tests__/IntegrationTestDetailsView.spec.tsx
  src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/components/PipelineRunDetailsView/PipelineRunEmptyState.tsx
  src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
  src/components/PipelineRunDetailsView/__tests__/PipelineRunEmptyState.spec.tsx
  src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
Labels: lgtm, approved

#328 Integration test Tab Edit test scenarios.
  integration-tests/support/pageObjects/global-po.ts
  integration-tests/support/pageObjects/pages-po.ts
  integration-tests/support/pages/tabs/IntegrationTestsTabPage.ts
  integration-tests/tests/add-component-to-application.spec.ts
Labels: lgtm

#324 Update review section loading message
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
Labels: lgtm, approved

#309 remove filter from Environments view
  src/components/Environment/EnvironmentListView.tsx
  src/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
  src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/hacbs/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
Labels: lgtm, approved

#334 remove route option from component settings
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
Labels: lgtm, approved

#330 Make environments read only
  src/components/ApplicationDetails/ApplicationDetails.tsx
  src/components/ApplicationDetails/DetailsPage.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts
  src/components/Environment/EnvironmentListView.tsx
  src/components/Environment/__tests__/EnvironmentCard.spec.tsx
  src/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/components/Environment/__tests__/environment-utils.spec.ts
  src/components/Environment/environment-actions.ts
  src/components/Environment/environment-utils.ts
  src/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
  src/hacbs/components/Environment/EnvironmentCard.tsx
  src/hacbs/components/Environment/EnvironmentListView.tsx
  src/hacbs/components/Environment/EnvironmentToolbarGroups.tsx
  src/hacbs/components/Environment/__tests__/EnvironmentCard.spec.tsx
  src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/hacbs/components/Environment/utils.ts
  src/hacbs/components/WorkspaceSettings/WorkspaceSettings.tsx
  src/hacbs/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
  src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts
  src/hooks/useAllEnvironments.ts
Labels: lgtm, approved

#337 Add skip initial check annotation while creating components
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#322 update validation text
  integration-tests/support/pages/AddComponentPage.ts
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
Labels: lgtm, approved

#338 Add spin animation to running build status icon
  src/utils/gitops-utils.scss
  src/utils/gitops-utils.tsx
Labels: lgtm, approved

#329 Fix tests.
  integration-tests/config/hac-dev-default.json
  pr_check.sh
Labels: lgtm, approved

#343 Upgrade formik-pf to fix submit errors and fix e2e tests
  integration-tests/support/pages/AddComponentPage.ts
  integration-tests/support/pages/AddIntegrationTestPage.ts
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/support/pages/CreateApplicationPage.ts
  integration-tests/support/pages/CreateBuildPage.ts
  integration-tests/utils/Applications.ts
  package-lock.json
  package.json
Labels: lgtm, approved

#333 reduce default resources
  src/components/ImportForm/utils/__tests__/transform-utils.spec.ts
  src/components/ImportForm/utils/transform-utils.ts
Labels: lgtm, approved

#336 fix environment variables deletion while updating a component
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#345 Redirect components tab from component settings page
  src/components/ComponentSettingsForm/ComponentSettingsView.tsx
Labels: lgtm, approved

#346 Update the instructions to fork samples
  src/components/ImportForm/SampleSection/SampleInfoAlert.tsx
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SourceSection/SourceSection.tsx
Labels: lgtm, approved

#339 fix initial pipelinerun status text and duration field
  src/components/Commits/__tests__/commit-status.spec.ts
  src/components/Commits/commit-status.ts
  src/components/PipelineRunListView/PipelineRunListRow.tsx
  src/shared/components/pipeline-run-logs/__tests__/utils.spec.ts
  src/shared/components/pipeline-run-logs/utils.ts
Labels: lgtm, approved

#331 update commit list view and add activity view
  src/components/Activity/ActivityTab.scss
  src/components/Activity/ActivityTab.tsx
  src/components/Activity/__tests__/ActivityTab.spec.tsx
  src/components/ApplicationDetails/ApplicationDetails.scss
  src/components/ApplicationDetails/ApplicationDetails.tsx
  src/components/Commits/CommitsListHeader.tsx
  src/components/Commits/CommitsListRow.scss
  src/components/Commits/CommitsListRow.tsx
  src/components/Commits/CommitsListView.tsx
  src/components/Commits/__data__/pipeline-with-commits.ts
  src/components/Commits/__tests__/CommitsListRow.spec.tsx
  src/components/Commits/__tests__/CommitsListView.spec.tsx
  src/components/PipelineRunListView/PipelineRunsListView.tsx
  src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
  src/consts/pipelinerun.ts
  src/imgs/code-commit.svg
  src/imgs/code-pull-request.svg
  src/types/commit.ts
  src/utils/commits-utils.ts
Labels: lgtm, approved

#332 Show routes as component URL on component cards
  integration-tests/support/pageObjects/createApplication-po.ts
  src/components/ComponentsListView/ComponentListItem.tsx
  src/components/ComponentsListView/__tests__/ComponentListItem.spec.tsx
  src/hooks/__data__/mock-data.ts
  src/utils/__tests__/route-utils.spec.ts
Labels: lgtm, approved

#348 view build logs should only show the build pipelinerun logs
  src/components/LogViewer/BuildLogViewer.tsx
  src/components/LogViewer/__tests__/BuildLogViewer.spec.tsx
  src/hooks/useComponentPipelineRun.tsx
Labels: lgtm, approved

#340 Add status icon to the commit list status column
  src/components/Commits/CommitDetailsView.tsx
  src/components/Commits/CommitsListRow.tsx
  src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/shared/components/pipeline-run-logs/StatusIcon.tsx
Labels: lgtm, approved

#349 read PR number from pipeline run label
  src/components/Commits/__data__/pipeline-with-commits.ts
  src/utils/__tests__/commits-utils.spec.ts
  src/utils/commits-utils.ts
Labels: lgtm, approved

#341 Fix disappearing advanced options when switching runtime
  src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
  src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
Labels: lgtm, approved

#355 remove Stonesoup referenece from component description
  src/components/Components/ComponentListView.tsx
Labels: lgtm, approved

#351 add component reference to pipeline run details
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
Labels: lgtm, approved

#361 Fix cancelling status alignment
  src/shared/components/pipeline-run-logs/StatusIcon.tsx
Labels: lgtm, approved

#353 remove case sensitive filters in the commit list view
  src/components/Commits/CommitsListView.tsx
  src/components/Commits/__data__/pipeline-with-commits.ts
  src/components/Commits/__tests__/CommitsListRow.spec.tsx
  src/components/Commits/__tests__/CommitsListView.spec.tsx
  src/utils/__tests__/commits-utils.spec.ts
  src/utils/commits-utils.ts
Labels: lgtm, approved

#359 Fix environment status in env list view and graph nodes
  src/components/ApplicationDetails/tabs/overview/sections/__data__/WorkflowSnapshotsEnvironmentBindingsData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useCommitWorkflowData.spec.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/useCommitWorkflowData.ts
  src/consts/pipelinerun.ts
  src/hacbs/components/Environment/__data__/mockAppEnvWithHealthStatus.ts
  src/hacbs/components/Environment/__tests__/EnvironmentCard.spec.tsx
  src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
  src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts
  src/hooks/useSnapshots.ts
  src/types/coreBuildService.ts
  src/types/pipeline-run.ts
  src/utils/__tests__/environment-utils.spec.ts
  src/utils/environment-utils.ts
Labels: lgtm, approved

#347 Update AppStudio Component build annotations
  helpers/resources/component.yaml
  helpers/setup.sh
  src/components/ApplicationDetails/tabs/overview/sections/__data__/WorkflowComponentsData.ts
  src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
  src/components/Components/BuildStatusColumn.tsx
  src/components/Components/ComponentListView.tsx
  src/components/Components/__data__/mock-data.ts
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#363 remove explore documentation link from action dropdown in application details view
  src/components/ApplicationDetails/ApplicationDetails.tsx
Labels: lgtm, approved

#362 Merged hac-dev test reports into the appstudio-qe report portal
  integration-tests/config/hac-dev-default.json
  integration-tests/config/hac-dev-experimental.json
Labels: lgtm, approved

#360 Fix navigation for activity page tab items
  config/remotePlugin.js
  src/components/Activity/ActivityTab.tsx
  src/components/Activity/__tests__/ActivityTab.spec.tsx
  src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
  src/components/Commits/CommitsListView.tsx
  src/components/Commits/__tests__/CommitsListView.spec.tsx
  src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
  src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/components/WorkspaceSettings/WorkspaceSettings.tsx
  src/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
  src/hacbs/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
Labels: lgtm, approved

#357 change browser tab title based on different views
  src/components/ApplicationDetails/ApplicationDetails.tsx
  src/components/ApplicationDetails/DetailsPage.tsx
  src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
  src/components/Commits/CommitDetailsView.tsx
  src/components/HeadTitle.tsx
  src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/components/IntegrationTest/IntegrationTestDetailsView.tsx
  src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
  src/pages/ApplicationDetailsPage.tsx
  src/pages/ApplicationsPage.tsx
  src/pages/CommitsPage.tsx
  src/pages/ComponentSettingsPage.tsx
  src/pages/ImportPage.tsx
  src/pages/IntegrationTestDetailsPage.tsx
  src/pages/PipelineRunPage.tsx
Labels: lgtm, approved

#356 add component column to pipelinerun list
  src/components/PipelineRunListView/PipelineRunListHeader.ts
  src/components/PipelineRunListView/PipelineRunListRow.tsx
  src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
Labels: lgtm

#369 Speed up PR check job
  package.json
Labels: lgtm, approved

#375 add commit link in pipeline run details page
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
Labels: lgtm, approved

#374 modify sample page filter to match the results based on tags
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx
Labels: lgtm, approved

#367 replace Stonesoup with CI/CD for now in browser titles
  src/components/ApplicationDetails/DetailsPage.tsx
  src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
  src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
  src/components/ImportForm/ReviewSection/ReviewSection.tsx
  src/components/ImportForm/SampleSection/SampleSection.tsx
  src/components/ImportForm/SourceSection/SourceSection.tsx
  src/pages/ApplicationsPage.tsx
  src/pages/ComponentSettingsPage.tsx
Labels: lgtm, approved

#373 running icon speed should be consistent
  src/shared/components/pipeline-run-logs/StatusIcon.scss
  src/shared/components/pipeline-run-logs/StatusIcon.tsx
Labels: lgtm, approved

#376 fix last deploy time in application list view
  src/components/ApplicationListView/ApplicationListRow.tsx
  src/components/ApplicationListView/__tests__/ApplicationListRow.spec.tsx
Labels: lgtm, approved
