Repository openshift/hac-dev, pull requests merged in 2024-07, with the labels that each got.

#959 Test pr check
  pr_check.sh
Labels: lgtm, ok-to-test

#958 fix(test): update Pipeline label value in pipeline run details view
  integration-tests/tests/advanced-happy-path.spec.ts
  pr_check.sh
Labels: lgtm, approved

#953 feat(pipelinerun): add snapshot creation message
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/consts/pipelinerun.ts
Labels: lgtm, approved

#955 fix(ImageRepository): add notification data and generate sbom url
  src/components/ImportForm/GitImportForm.tsx
  src/components/ImportForm/__tests__/GitImportForm.spec.tsx
  src/components/ImportForm/__tests__/submit-utils.spec.ts
  src/components/ImportForm/submit-utils.ts
  src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
  src/hooks/__tests__/useApplicationPipelineGithubApp.spec.ts
  src/hooks/__tests__/useStoneSoupGitHubApp.spec.ts
  src/hooks/__tests__/useUIInstance.spec.ts
  src/hooks/useApplicationPipelineGitHubApp.ts
  src/hooks/useUIInstance.ts
  src/types/image-repository.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#960 fix(PipelineRunDetailsTab): support deprecated pipeline run for view sbom
  src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
  src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
  src/utils/pipeline-utils.ts
Labels: lgtm, approved

#962 ci: switch back to main cicd-tools branch
  pr_check.sh
Labels: lgtm, ok-to-test, approved

#957 Use new git location for ec pipeline definition
  src/components/IntegrationTest/IntegrationTestForm/const.ts
Labels: lgtm, ok-to-test, approved

#944 Update CVE Modal fields and Issues output
  src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueModal.tsx
  src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueSection.tsx
  src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/CVEComponentDropDown.tsx
  src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/CVEFormContent.tsx
  src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/ComponentField.tsx
  src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/CVEFormContent.spec.tsx
  src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/ComponentField.spec.tsx
  src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/form-utils.spec.ts
  src/components/ReleaseService/ReleasePlan/TriggerRelease/form-utils.ts
  src/types/coreBuildService.ts
Labels: lgtm, approved

#963 test: add a test for a private repo
  integration-tests/cypress.config.ts
  integration-tests/support/pageObjects/createApplication-po.ts
  integration-tests/support/pages/AddComponentPage.ts
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/basic-happy-path.spec.ts
  integration-tests/tests/create-application-from-private-git-form.spec.ts
  integration-tests/tests/private-basic-application.spec.ts
  integration-tests/utils/APIHelper.ts
  integration-tests/utils/Applications.ts
  integration-tests/utils/UIhelper.ts
  pr_check.sh
Labels: lgtm, approved

#965 test: stabilize tests by skipping failing ones
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/utils/UIhelper.ts
Labels: lgtm, approved

#966 feat: add and use docker-build-oci-ta as default
  src/components/ImportForm/PipelineSection/__tests__/usePipelineTemplate.spec.ts
  src/components/ImportForm/PipelineSection/usePipelineTemplate.ts
Labels: lgtm, ok-to-test, approved
