Repository openshift/hac-dev, pull requests merged in 2024-06, with the labels that each got.

#938 chore(main): release rhtap-ui 0.5.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: approved, autorelease: pending

#939 fix(import): do not send generate annotation in component
  src/utils/__tests__/create-utils.spec.ts
  src/utils/create-utils.ts
Labels: lgtm, approved

#940 fix(ImportFlow): add input field for docker file path
  src/components/ImportForm/ComponentSection/ComponentSection.tsx
  src/components/ImportForm/type.ts
Labels: lgtm, approved

#942 fix(ImageRepository): add iimage controller annontation while create IR cr
  src/utils/create-utils.ts
Labels: lgtm, approved

#937 fix(e2e): fix basic happy path
  integration-tests/cypress.config.ts
  integration-tests/support/pageObjects/createApplication-po.ts
  integration-tests/support/pages/AddComponentPage.ts
  integration-tests/support/pages/ApplicationDetailPage.ts
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/support/pages/CreateApplicationPage.ts
  integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
  integration-tests/support/pages/tabs/OverviewTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/basic-happy-path.spec.ts
  integration-tests/tests/create-application-from-public-git-source.spec.ts
  integration-tests/tests/create-application-from-sample.spec.ts
  integration-tests/utils/APIHelper.ts
  integration-tests/utils/Applications.ts
Labels: lgtm, approved

#943 fix(BuildPipeline): filter pipeine run based on sender annotation
  src/hooks/usePACState.ts
  src/hooks/usePACStatesForComponents.ts
Labels: lgtm, approved

#947 fix: show data for build image and commit author
  src/components/Commits/__data__/pipeline-with-commits.ts
  src/components/Components/ComponentDetails/__data__/mockComponentDetails.ts
  src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx
  src/utils/commits-utils.ts
Labels: lgtm, approved

#935 fix(SecretListPage): add workspace breadcrumbs on secrets list page
  config/remotePlugin.js
  src/pages/SecretsListPage.tsx
  src/pages/WorkspacedPage.tsx
  src/pages/__tests__/SecretsListPage.spec.tsx
  src/pages/__tests__/WorkspacedPage.spec.tsx
Labels: lgtm, approved

#946 Fix advanced happy path
  integration-tests/support/pageObjects/createApplication-po.ts
  integration-tests/support/pages/ComponentsPage.ts
  integration-tests/support/pages/SecretsPage.ts
  integration-tests/support/pages/tabs/IntegrationTestsTabPage.ts
  integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
  integration-tests/tests/advanced-happy-path.spec.ts
  integration-tests/tests/basic-happy-path.spec.ts
  integration-tests/utils/Applications.ts
Labels: lgtm, approved

#948 test: add prefix for username
  pr_check.sh
Labels: lgtm, approved

#951 fix(test): don't remove repo if test failed to easy failure debugging
  integration-tests/tests/basic-happy-path.spec.ts
Labels: lgtm, approved

#945 fix(GitRepoLink): add support for gitlab.cee.redhat.com urls
  src/components/GitLink/GitRepoLink.tsx
  src/components/GitLink/__tests__/GitRepoLink.spec.tsx
  src/utils/__tests__/git-utils.spec.tsx
  src/utils/git-utils.tsx
Labels: lgtm, approved

#949 fix(release): remove release strategy
  src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListHeader.tsx
  src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListRow.tsx
  src/components/ReleaseService/ReleasePlanAdmission/__tests__/ReleasePlanAdmissionListRow.spec.tsx
  src/components/ReleaseService/ReleaseService.tsx
  src/components/ReleaseService/ReleaseStrategy/ReleaseStrategyListHeader.tsx
  src/components/ReleaseService/ReleaseStrategy/ReleaseStrategyListRow.tsx
  src/components/ReleaseService/ReleaseStrategy/ReleaseStrategyListView.tsx
  src/components/ReleaseService/ReleaseStrategy/__data__/release-strategy.mock.ts
  src/components/ReleaseService/ReleaseStrategy/__tests__/ReleasePlanListRow.spec.tsx
  src/components/ReleaseService/ReleaseStrategy/__tests__/ReleasePlanListView.spec.tsx
  src/components/ReleaseService/ReleaseStrategy/releasestrategy-actions.tsx
Labels: lgtm, approved

#950 fix(secret): link serviceaccount
  src/components/ImportForm/__tests__/GitImportForm.spec.tsx
  src/components/Secrets/__tests___/secret-actions.spec.ts
  src/components/Secrets/secret-actions.ts
  src/components/Secrets/utils/__tests__/service-account-utils.spec.ts
  src/components/Secrets/utils/service-account-utils.ts
  src/types/secret.ts
Labels: lgtm, approved

#952 fix(test): don't verify certificate
  tmp/keycloak.py
Labels: lgtm, approved

#954 chore(main): release rhtap-ui 0.5.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: lgtm, approved, autorelease: pending
